-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2025-02-25 15:28:43 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g



DROP TABLE MC_DIM_CATEGORIA_PRODUTO CASCADE CONSTRAINTS 
;

DROP TABLE MC_DIM_CENTRO_DISTRIBUICAO CASCADE CONSTRAINTS 
;

DROP TABLE MC_DIM_FORNECEDOR CASCADE CONSTRAINTS 
;

DROP TABLE MC_DIM_PRODUTO CASCADE CONSTRAINTS 
;

DROP TABLE MC_DIM_TEMPO CASCADE CONSTRAINTS 
;

DROP TABLE MC_FATO_ESTOQUE CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE


-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
